import { Button } from "@mui/material";
import { height } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [piso, setPiso] = useState(6);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ position: "relative" }}>
        <Image
          src="/img/edificio-de-oficinas.png"
          width={700}
          height={700}
          layout="fixed"
          alt="edificio"
        />
        <div
          style={{
            background: "red",
            width: 47.1,
            height: 47.1,
            position: "absolute",
            top: 110,
            left: 317,
            transform: `translate(10px,${0 + (6 - piso) * 94.1}px)`,
            transition: "all ease 2s",
          }}
        ></div>
        <div
          style={{
            background: "black",
            width: 4.1,
            height: 20.1,
            position: "absolute",
            top: 138,
            left: 427,
          }}
        ></div>
        <div
          style={{
            background: "black",
            width: 4.1,
            height: 17.1,
            position: "absolute",
            top: 140,
            left: 437,
          }}
        ></div>
      </div>
      <Button onClick={() => piso !== 6 && setPiso(piso + 1)}>subir</Button>
      <Button onClick={() => piso !== 1 && setPiso(piso - 1)}>bajar</Button>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
